src/main/java/restaurante/controle/CaixaEntradaBean.java
package restaurante.controle;

import java.util.List;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import restaurante.modelo.caixa.Caixa;
import restaurante.modelo.caixaEntrada.CaixaEntrada;
import restaurante.modelo.caixaEntrada.CaixaEntradaRN;
import restaurante.modelo.funcionario.Funcionario;

/**
 * 
 * @author IsaíasSantana
 *
 */
@ManagedBean
@ApplicationScoped
public class CaixaEntradaBean {
	
	private CaixaEntrada caixaEntrada;
	private Caixa caixa;
	private Funcionario funcionarioResponsavel;
	
	public CaixaEntradaBean(){
		caixaEntrada = new CaixaEntrada();
		caixa = new Caixa();
		funcionarioResponsavel = new Funcionario();
	}
	
	public Funcionario getFuncionarioResponsavel() {
		return funcionarioResponsavel;
	}

	public void setFuncionarioResponsavel(Funcionario funcionarioResponsavel) {
		this.funcionarioResponsavel = funcionarioResponsavel;
	}

	public CaixaEntrada getCaixaEntrada() {
		return caixaEntrada;
	}

	public void setCaixaEntrada(CaixaEntrada caixaEntrada) {
		this.caixaEntrada = caixaEntrada;
	}
	
	
	public Caixa getCaixa() {
		return caixa;
	}

	public void setCaixa(Caixa caixa) {
		this.caixa = caixa;
	}

	public List<Caixa> getListaCaixas(){
		return new CaixaEntradaRN().caixas();
	}
	
	public List<CaixaEntrada> getListaCaixaEntradas(){
		return new CaixaEntradaRN().listaCaixaEntradas();
	}
	
	public void setResponsavel(Funcionario funcionario){
		this.funcionarioResponsavel = funcionario;
	}
	
	/**
	 * Salva uma entrada de dinheiro no caixa.
	 */
	public void salvar()
	{
		CaixaEntradaRN cERN = new CaixaEntradaRN();
		caixaEntrada.setCaixa(caixa);
		cERN.cadastradaEntradaCaixa(caixaEntrada);
	}
	
}

src/main/webapp/gerente/buscarFuncionarioPorNome.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>
			<main>     
				<section class="pedido">
					<p:messages />
					
					<h:panelGrid columns="1">
								<h:form>
								 	<p:outputLabel value="Nome do funcionário: " for="nomeFunc"/>
								 	<p:inputText  id="nomeFunc" required="true" requiredMessage="Informe o nome do funcionário" value="#{funcionarioBean.funcionarioSelecionado.nome}"/> 
						 		</h:form>	
						 		
						 		<p:commandButton value="Buscar." action="#{funcionarioBean.buscaPorNome()}"  ajax="false" />
								 	
									<p:dataTable id="listaFuncionariosNome"
										value="#{funcionarioBean.listaFuncionarioPorNome}" var="funcionario"
										emptyMessage="Nenhum funcionário econtrado com esse nome." rendered="#{not empty funcionarioBean.listaFuncionarioPorNome}">
										<f:facet name="header">
					         			 	Funcionários encontrados.
					      			 	</f:facet>
										
										<p:column headerText="ID">
					      			 		<p:outputLabel value="#{funcionario.idFuncionario}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Nome">
					      			 		<p:outputLabel value="#{funcionario.nome}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Salário">
					      			 		<p:outputLabel value="#{funcionario.salarioBase}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Carga horária base">
					      			 		<p:outputLabel value="#{funcionario.cargaHorariaBase}"/>
					      			 	</p:column>
					      			 
					      			 	<p:column headerText="Carga horária trabalhada">
					      			 		<p:outputLabel value="#{funcionario.cargaHorariaTrabalhada}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Categoria">
					      			 		<p:outputLabel value="#{funcionario.categoria}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Cpf">
					      			 		<p:outputLabel value="#{funcionario.cpf}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="horas extras">
					      			 		<p:outputLabel value="#{funcionario.horasExtras}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Status contratual">
					      			 		<p:outputLabel value="#{funcionario.statusContratual}"/>
					      			 	</p:column>
					      			 	
					      			 	<p:column headerText="Quadro de horário">
					      			 		<p:commandButton onclick="PF('dlg3').show();" value="Ver quadro de horário">
					      			 			
					      			 		</p:commandButton>
					      			 		
					      			 		<p:dialog header="Quadro de horário" widgetVar="dlg3" height="100">
											
											<p:panelGrid columns="2">
												<p:outputLabel value="ID: "/>
												<p:outputLabel value="#{funcionario.quadroHorario.idQuadroHorarios}"/>
												
												<p:outputLabel value="hora de chegada: "/>
												<p:outputLabel value="#{funcionario.quadroHorario.horaDeChegada}"/>
												
												<p:outputLabel value="hora de saída: "/>
												<p:outputLabel value="#{funcionario.quadroHorario.horaDeSaida}"/>
												
											</p:panelGrid>
											
										</p:dialog>
					      			 		
					      			 	</p:column>
					      			 	
					      			 	
					      			 	
					      			</p:dataTable>
	
						 						
					</h:panelGrid>
					
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/cadastraRetiradaCaixa.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>
			
			<script>
				function configurarMoeda() {
					$(".moeda").maskMoney({
						decimal : ",",
						thousands : ".",
						allowZero : true
					});
				}

				$(document).ready(function() {
					configurarMoeda();
				});
			</script>
			
			<main>     
				<section class="pedido">
					<p:messages/>
					<h1> <p:outputLabel value="Controle do caixa: Retirada do caixa"/> </h1>
					<br/> <h:panelGrid columns="2">
						<p:outputLabel value="Valor a ser retirado: " for="valor"/>
						<p:inputText id="valor" value="#{caixaRetiradaBean.caixaRetirada.valor}" styleClass="moeda" required="true" requiredMessage="Com qual valor será retirado do caixa ?">
							<f:convertNumber pattern="#,##0.00" locale="pt_BR"
									maxFractionDigits="2" />
								<f:validateDoubleRange minimum="0.00" />
						</p:inputText>
						<p:outputLabel value="Escolha o caixa para a retirada: " for="caixa"/>
						
						<p:selectOneMenu id="caixa" value="#{caixaRetiradaBean.caixaRetirada.caixa}" converter="caixaConverter" style="width:125px" required="true" requiredMessage="Escolha um caixa para depósito.">
				            <f:selectItem itemLabel="Selecione" itemValue="" />
				            <f:selectItems value="#{caixaEntradaBean.listaCaixas}" var="caixa" itemLabel="#{caixa.idCaixa}" itemValue="#{caixa}"/>
				        </p:selectOneMenu>
						
						<p:outputLabel value="Funcionário responsável: " for="funcRes"/>
						<p:commandButton id="funcRes" onclick="PF('dialogoFuncionario').show();" value="Selecionar funcionário"/>
						
					
						<p:dialog header="Lista funcionários" widgetVar="dialogoFuncionario" height="100">
							<p:dataTable var="funcionario" value="#{funcionarioBean.listaFuncionarios}">
								<f:facet name="header">
					         		Selecione um funcionário
					      		</f:facet>
							 	<p:column headerText="Nome">
							 		<p:outputLabel value="#{funcionario.nome}"/>
							 	</p:column>
							 	<p:column headerText="Cpf">
							 		<p:outputLabel value="#{funcionario.cpf}"/>
							 	</p:column>
							 	<p:column headerText="Categoria">
							 		<p:outputLabel value="#{funcionario.categoria}"/>
							 	</p:column>
							 	<p:column>
							 		<p:commandButton value="Selecionar" onclick="PF('dialogoFuncionario').hide();">
							 			<f:setPropertyActionListener value="#{funcionario.idFuncionario}"
													target="#{caixaRetiradaBean.caixaRetirada.responsavel}" />
							 		</p:commandButton>
							 	</p:column>
							</p:dataTable>
						</p:dialog>
						
						<p:commandButton value="Cadastrar entrada no caixa" action="#{caixaRetiradaBean.salvar()}"  ajax="false"/>
					</h:panelGrid>
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/cadastrarFuncionario.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>

			<script>
				function configurarMoeda() {
					$(".moeda").maskMoney({
						decimal : ",",
						thousands : ".",
						allowZero : true
					});
				}

				$(document).ready(function() {
					configurarMoeda();
				});
			</script>

			<main>
			<h2>Novo funcionário</h2>
			<section class="pedido">
				<p:messages />
				<table>
					<tr>
						<td><p:outputLabel value="Nome " for="nome" /></td>
						<td><p:inputText id="nome" required="true" 
								requiredMessage="O funcionário deve possuir um nome."
								value="#{funcionarioBean.funcionario.nome}" /></td>
					</tr>

					<tr>
						<td><p:outputLabel value="Cpf" for="cpf" /></td>
						<td><p:inputMask mask="999.999.999-99" id="cpf"
								required="true" requiredMessage="Qual o cpf do funcionário ?"
								value="#{funcionarioBean.funcionario.cpf}" /></td>
					</tr>

					<tr>
						<td><p:outputLabel value="Salário base" for="sBase" /></td>
						<td><p:inputText id="sBase" styleClass="moeda"
								value="#{funcionarioBean.funcionario.salarioBase}"
								required="true"
								requiredMessage="É preciso saber o salário do funcionário.">
								<f:convertNumber pattern="#,##0.00" locale="pt_BR"
									maxFractionDigits="2" />
								<f:validateDoubleRange minimum="400.00" />
							</p:inputText></td>
					</tr>

					<tr>
						<td><p:outputLabel value="Carga horária base" for="chb" /></td>
						<td><p:inputText id="chb"
								value="#{funcionarioBean.funcionario.cargaHorariaBase}"
								required="true"
								requiredMessage="Qual a carga horária de trabalho do funcionário ?" /></td>
					</tr>

					<tr>
						<td><p:outputLabel value="Carga horária trabalhada" for="cht" /></td>
						<td><p:calendar locale="pt" id="cht"
								value="#{funcionarioBean.funcionario.cargaHorariaTrabalhada}"
								pattern="HH:mm" timeOnly="true" required="true"
								requiredMessage="É nescessário informar a carga horária trabalhada." /></td>

					</tr>
					
					<tr>
						<td><p:outputLabel value="Horas extras" for="horasExtras"/></td>
						<td><p:calendar locale="pt" id="horasExtras"
								value="#{funcionarioBean.funcionario.horasExtras}"
								pattern="HH:mm" timeOnly="true" required="true"
								requiredMessage="É nescessário informar as horas extras do funcionário." /></td>
					</tr>
					
					<tr>
						<td><p:outputLabel value="Status contratual" for="statusContrato"/></td>
						<td>
							<p:inputText id="statusContrato" value="#{funcionarioBean.funcionario.statusContratual}" required="true">
								<f:validateDoubleRange minimum="1" />
							</p:inputText>
					   </td>
					</tr>
					
					<tr>
						<td><p:outputLabel value="Tipo do funcionário" for="tipoFunc" /></td>
						<td><p:selectOneRadio id="tipoFunc"
								value="#{funcionarioBean.funcionario.categoria}"
								required="true" requiredMessage="Qual o tipo do funcionário ?">
								<f:selectItem itemLabel="Garçom" itemValue="garcom" />
								<f:selectItem itemLabel="Gerente" itemValue="gerente" />
								<f:selectItem itemLabel="Estoquista" itemValue="estoquista" />
								<f:selectItem itemLabel="Cozinheiro" itemValue="cozinheiro" />
							</p:selectOneRadio></td>
					</tr>
					
					<tr>
						<td>
							<p:outputLabel value="Quadro de horário"/>
						</td>
						
						<td>
							 <p:commandButton value="Selecionar" type="button" onclick="PF('dlg2').show();" />
							<!--<p:inputText id="qh" onclick="PF('dlg2').show();" required="true" requiredMessage="É preciso de um quadro de horário para o funcionario."/>-->
							<p:dialog header="Modal Dialog" widgetVar="dlg2" modal="true" height="100">
									<p:dataTable id="listarFornecedor"
										value="#{quadroHorariosBean.quadroHorariosList}" var="QuadroHorario"
										emptyMessage="Nenhum Quadro de horário encontrado.">
										<f:facet name="header">
					         			 	Quadro de horários
					      			 	</f:facet>
										<p:column headerText="Código">
											<h:outputText value="#{QuadroHorario.idQuadroHorarios}" />
										</p:column>
										<p:column headerText="Hora de entrada">
											<h:outputText value="#{QuadroHorario.horaDeChegada}" />
										</p:column>
										<p:column headerText="Hora de saída">
											<h:outputText value="#{QuadroHorario.horaDeSaida}" />
										</p:column>
										
										<p:column headerText="Selecionar">
											<p:commandButton  partialSubmit="true" action="#{funcionarioBean.escolherQuadroHorario}" value="Selecionar" title="Selecionar quadro de horário do funcionário."  onclick="PF('dlg2').hide();">
												<f:setPropertyActionListener value="#{QuadroHorario}"
													target="#{funcionarioBean.quadroHorario}" />
											</p:commandButton>
											
										</p:column>
									</p:dataTable>
    							<h:outputText value="This is a Modal Dialog." />
							</p:dialog>
						</td>
						
					</tr>
					
					<tr>
						<td><p:commandButton value="Cadastrar funcionario"
								update="@form" process="@form"
								action="#{funcionarioBean.salvar}" /></td>
					</tr>
				</table>
			</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/cadastroCaixa.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>
			<main>     
				<section class="pedido">
					<h1> <p:outputLabel value="Novo caixa"/> </h1>
					<p:messages/>
					<h:panelGrid columns="2">
						<p:outputLabel value="Identificador do caixa" for="idCaixa"/>
						<p:inputText id="idCaixa" required="true" requiredMessage="Por favor, informe um identificador para o caixa" value="#{caixaBean.caixa.idCaixa}"/>
						<p:outputLabel value="Funcionário responsável pela abertura e fechamento do caixa:  " for="gerente"/>
				        <p:selectOneMenu converter="funcionarioConverter" id="gerente" value="#{caixaBean.funcionarioResponsavel}" required="true" requiredMessage="Escolha o gerente que gerência esse caixa.">
				            <f:selectItems value="#{caixaBean.gerentes}" var="func" itemValue="#{func}"/>
				            
				        </p:selectOneMenu>
				        <p:commandButton action="#{caixaBean.salvar()}" value="Cadastrar Caixa" ajax="false"/>
					</h:panelGrid>
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/cadastroQuadroHorario.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
		
	<ui:define name="conteudo">
		<h:form>
			
			<main>
				<h2>Novo quadro de horário</h2>
				<section class="pedido">
					<p:messages />
					<table>
						<tr>
							<td><p:outputLabel value="Hora de chegada" for="horaChegada" /></td>
							<td><p:calendar  locale="pt" id="horaChegada"   value="#{quadroHorariosBean.quadroHorarios.horaDeChegada}" pattern="HH:mm:ss" timeOnly="true"  required="true" requiredMessage="É nescessário informar a hora de chegada dos funcionários para esse quadro de horário."/></td>
						</tr>
						
						<tr>
							<td><p:outputLabel value="Hora de saída" for="horaSaida" /></td>
							<td><p:calendar locale="pt" id="horaSaida" value="#{quadroHorariosBean.quadroHorarios.horaDeSaida}" pattern="HH:mm:ss" timeOnly="true"  required="true" requiredMessage="É nescessário informar a hora de saída dos funcionários para esse quadro de horário."/></td>
						</tr>
												
						<tr>
							<td>
								<p:commandButton  value="salvar quadro de horário" update="@form" process="@form"  action="#{quadroHorariosBean.salvar}"/>
							</td>
						</tr>
					</table>
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/cardapio.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="description" content="Sistema de Restaurante"/>
		<meta name="author" content="Danilo Ramos"/>
		<h:outputStylesheet library="css" name="style.css"/> 
		<title>Gerenciar Cardápio</title>
	</h:head>
	<h:body>
		
		<header class="head">
					<table>
						<tr>
							<td> <p:graphicImage library="img" name="logo.png" width = "150" height = "150"/></td>
						<td>
							<table>
								<tr>
									<td><h1>Cantina de Mos Eisley</h1></td>
								</tr>
								<tr>
									<td><p:graphicImage library="img" name="moseisley.png" width = "388" height = "100"/></td>
								</tr>
							</table>
						</td>
					</tr>				
				</table>
		</header>
		
		<aside class = "menu_gerente">
				<h3>Olá Han Solo!</h3>
				<h4>O que deseja fazer?</h4>
				<table>
					<tr>
						<td><h3>Gerenciar Comandas</h3></td>
					</tr>
					<tr>				
						<td><a href="listaComandasAtivas.jsf">Comandas Ativas</a></td>
					</tr>
					<tr>
						<td><a href="listaComandasInativas.jsf">Comandas Inativas</a></td>
					</tr>
					<tr>
						<td><h3>Gerenciar Pedidos</h3></td>
					</tr>
					<tr>				
						<td><a href="listaPedidos.jsf">Listar Pedidos</a></td>
					</tr>
					<tr>
						<td><h3>Gerencia de Cardápio</h3></td>
					</tr>
					<tr>
						<td><h3>Gerenciar Pessoal</h3></td>
					</tr>
					<tr>
						<td><a href="listarQuadroHorarios.jsf">Listar Quadro de Horários</a></td>
					</tr>
					<tr>
						<td><a href="cadastroQuadroHorario.jsf">Cadastrar Quadro de Horários</a></td>
					</tr>
					<tr>
						<td><a href="cadastrarFuncionario.jsf">Listar Funcionarios</a></td>
					</tr>
					<tr>
						<td><a href="cadastrarFuncionario.jsf">Novo Funcionario</a></td>
					</tr>
					
				</table>
			</aside>
		
			<main>
				<h1 style="margin-top:0">Gerenciar Cardápio</h1>
				<div class="pedido">
				<h:form>
				<p:messages />
				<p:dataTable id="cardapioRefeicao" value="#{produtoBean.listaRefeicao}" var="refeicao" 
					emptyMessage="Nenhuma refeição cadastrada!" >
						<f:facet name="header">
         			 	Refeições
      					 </f:facet>
						<p:column headerText="Código">
							<h:outputText value="#{refeicao.idProduto}" />
						</p:column>
						<p:column headerText="Nome">
							<h:outputText value="#{refeicao.nome}" />
						</p:column>
						<p:column headerText="Preço">
							R$: <h:outputText value="#{refeicao.preco}" >
								<f:convertNumber minFractionDigits="2" maxFractionDigits="2" />
							</h:outputText>
						</p:column>								
						<p:column headerText="Editar">
						<h:commandButton value="Editar" action="#{produtoBean.editar}">
						<f:setPropertyActionListener value="#{refeicao}" target="#{produtoBean.produto}" />
						</h:commandButton>
					</p:column>
					<p:column headerText="Excluir">
						<h:commandButton value="Excluir" action="#{produtoBean.excluir}" 
						onclick ="return confirm('Você deseja excluir a refeição selecionada?')">
							<f:setPropertyActionListener value="#{refeicao}" target="#{produtoBean.produto}" />
						</h:commandButton>
					</p:column>
				</p:dataTable>
				<p:dataTable id="cardapioBebidas" value="#{produtoBean.listaBebida}" var="bebida" 
					emptyMessage="Nenhum bebida cadastrada!" >
						<f:facet name="header">
         			 	Bebidas
      					 </f:facet>
						<p:column headerText="Código">
							<h:outputText value="#{bebida.idProduto}" />
						</p:column>
						<p:column headerText="Nome">
							<h:outputText value="#{bebida.nome}" />
						</p:column>
						<p:column headerText="Preço">
							R$: <h:outputText value="#{bebida.preco}" >
								<f:convertNumber minFractionDigits="2" maxFractionDigits="2" />
							</h:outputText>
						</p:column>								
						<p:column headerText="Editar">
						<h:commandButton value="Editar" action="#{produtoBean.editar}">
						<f:setPropertyActionListener value="#{bebida}" target="#{produtoBean.produto}" />
						</h:commandButton>
					</p:column>
					<p:column headerText="Excluir">
						<h:commandButton value="Excluir" action="#{produtoBean.excluir}" 
						onclick ="return confirm('Você deseja excluir a bebida selecionada?')">
							<f:setPropertyActionListener value="#{bebida}" target="#{produtoBean.produto}" />
						</h:commandButton>
					</p:column>
				</p:dataTable>
			</h:form>
			</div>
			<p:commandButton value="Novo Produto"  action="cadastroProduto">
					</p:commandButton>
			</main>
			
			
			
			<aside class = "login">
				<form>
					<table>
						<tr><td><h1>Perfil</h1></td></tr> <br/>
						<tr><td><p:graphicImage library="img" name="han.jpg" alt="han solo" width="130" height="160"/></td></tr>
						<tr><td><b>Nome:</b> Han Solo</td></tr>
						<tr><td><b>Função:</b> Gerente</td></tr>
						<tr><td><b>Turno:</b> Diurno</td></tr>
						<tr><td><b>Entrada:</b> 05:00</td></tr>
						<tr><td><b>Saida:</b> 00:00</td></tr>
						
						<tr><td><p:button target="index.xhtml" value="Logout"/></td></tr>
					</table>					
				</form>
			</aside>
			
	</h:body>
	
</html>

src/main/webapp/gerente/fechamentoCaixa.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>	
			<main>     
				<section class="pedido">
					<h1> <p:outputLabel value="Fechamento do caixa do dia"/>  </h1>
					<table>
						<tr>
							<td>
								<p:panelGrid columns="3" rendered="#{caixaBean.totalEntrada > 0}">
									<p:outputLabel value="Total de entradas"/>
									<p:outputLabel value="Total de saídas"/>
									<p:outputLabel value="Total do caixa"/>
									<p:outputLabel value="#{caixaBean.totalEntrada}"/>
									<p:outputLabel value="#{caixaBean.totalSaida}"/>
									<p:outputLabel value="#{caixaBean.caixa.totalCaixa}"/>
								</p:panelGrid>
							</td>
						
						</tr>
					</table>
					
					<p:commandButton value="fechar caixa" ajax="false" action="#{caixaBean.fecharCaixa()}"/>
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/gerente/listarRetiradasCaixa.xhtml
<ui:composition template="/WEB-INF/template/templateGerente.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<ui:define name="conteudo">
		<h:form>
			<main>
				<h2>Retiradas</h2>
				<section class="pedido">
					<p:dataTable value="#{caixaRetiradaBean.listaRetiradas}" var="retiradas">
						<p:column headerText="Valor">
							<p:outputLabel value="#{retiradas.valor}"/>
						</p:column>
						<p:column headerText="Caixa">
							<p:outputLabel value="#{retiradas.caixa.idCaixa}"/>
						</p:column>
						<p:column headerText="Funcionário responsável">
							<p:outputLabel value="#{retiradas.responsavel}"/>
						</p:column>
					</p:dataTable>
				</section>
			</main>
		</h:form>
	</ui:define>
</ui:composition>